### ISSUE TITLE
Dataset link is broken?

### ISSUE THREAD

**Issue by moratodpg** [chrise96/3D_building_reconstruction#3]
Congrats for the great work!
I would like to access the segmentation dataset, but the link seems to be broken.

**Comment by yueyisui** [comment]
yes, do you get the dataset? I need help.

**Comment by moratodpg** [comment]
Nop, @yueyisui, I have not received any response so far.

**Comment by chrise96** [comment]
Muted alerts for this repo... I updated the README, hope its still useful :)

**Comment by moratodpg** [comment]
@chrise96 Thanks! The link works now.
