### ISSUE TITLE
Dataset question.

### ISSUE THREAD

**Issue by yueyisui** [chrise96/3D_building_reconstruction#4]
Thanks for your work.
The data connection seems to be lost, is it possible to re-give the link to the data?

**Comment by Ting-Devin-Han** [comment]
> Thanks for your work. The data connection seems to be lost, is it possible to re-give the link to the data?

Hello, have you received the data? Best wishes.

**Comment by chrise96** [comment]
Sorry for the late reply! I updated the README with a new link
